---
- name: Simple Ansible Play
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure Local User Has SSH key Pair
      ansible.builtin.user:
        name: pslearner
        generate_ssh_key: true
- name: Ansible Manage Ubuntu Hosts
  hosts: ubuntu
  gather_facts: false
  tasks:
    - name: Ensure Key Based Authetication Works to Remote Hosts
      ansible.posix.authorized_key:
        user: pslearner
        manage_dir: true
        key: "{{ lookup('file', '/home/pslearner/.ssh/id_rsa.pub') }}"
    - name: Create Project Directory
      become: true
      ansible.builtin.file:
        path: /projects/project1
        state: directory